# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - make clean
    - make statik/statik.go

builds:
  - main: ./cmd/sorashell
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

archives:
  - replacements:
      darwin: Darwin

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
